# -*- coding: utf-8 -*-
"""text_model_hack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbuv9uaXV31XEFuMNjvgYvoSLTlY6hXx

Loading Dataset....
"""

!wget https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv

import pandas as pd

df = pd.read_csv("sms.tsv", sep="\t", header=None, names=["label", "message"])
df["label"] = df["label"].map({"ham": 0, "spam": 1})

X = df["message"]
y = df["label"]

"""Train Test Split...."""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

"""Model.."""

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])

model.fit(X_train, y_train)

"""Evaluate..."""

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))

"""Risk Function.."""

def text_risk_score(message):
    prob = model.predict_proba([message])[0][1]
    return prob * 100

from sklearn.metrics import accuracy_score

new_message = ["Win free money now"]
true_label = [1]

prediction = model.predict(new_message)

print("Prediction:", prediction[0])

acc = accuracy_score(true_label, prediction)
print("Single Input Accuracy: {:.2f}%".format(acc * 100))