# -*- coding: utf-8 -*-
"""text_cms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaOAtElLvPk7WleZO1Mle8qB-29j1t6J
"""

import sklearn
import pandas as pd
import numpy as np

print("Libraries are working ✅")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

!wget https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import pandas as pd

# Load data and prepare X, y
df = pd.read_csv("sms.tsv", sep="\t", header=None, names=["label", "message"])
df["label"] = df["label"].map({"ham": 0, "spam": 1})
X = df["message"]
y = df["label"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])

model.fit(X_train, y_train)

texts = [
    "Your account will be blocked, verify now",
    "Click here to claim your lottery prize",
    "Meeting scheduled at 3 PM",
    "Your OTP is 456789",
    "Congratulations, you won money"
]

labels = [1, 1, 0, 0, 1]
# 1 = Scam, 0 = Not Scam

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])

model.fit(X_train, y_train)

model.predict(["Verify your bank account immediately"])

import pickle
pickle.dump(model, open("text_model.pkl", "wb"))

from google.colab import files
files.download("text_model.pkl")

model.predict_proba(["Your account is blocked"])

def text_risk_score(message):
    prob = model.predict_proba([message])[0][1]   # scam probability
    return prob * 100

text_risk_score("URGENT! Verify your bank account now!")

def classify_risk(score):
    if score < 30:
        return "LOW RISK 🟢"
    elif score < 70:
        return "MEDIUM RISK 🟡"
    else:
        return "HIGH RISK 🔴"

score = text_risk_score("Verify your account immediately")
print(score)
print(classify_risk(score))

"""URL begins.."""

import re

def url_risk_score(message):
    urls = re.findall(r'(https?://\S+)', message)

    if not urls:
        return 0   # no URL → no URL risk

    score = 0
    url = urls[0]

    # Rule 1: http instead of https
    if url.startswith("http://"):
        score += 30

    # Rule 2: suspicious words
    suspicious_words = ["verify", "login", "bank", "update", "secure"]
    for word in suspicious_words:
        if word in url.lower():
            score += 15

    # Rule 3: long URL
    if len(url) > 50:
        score += 20

    return min(score, 100)

url_risk_score("Click here http://fakebank-login-verify.com/update")

msg = "URGENT! Verify your bank account now http://fakebank-login.com/update"

print("Text Risk:", text_risk_score(msg))
print("URL Risk:", url_risk_score(msg))
print("Final Risk:", final_risk_score(msg))
print("Classification:", classify_risk(final_risk_score(msg)))

"""Combining both"""

def analyze_message(message):
    text_score = text_risk_score(message)
    url_score = url_risk_score(message)
    final_score = final_risk_score(message)
    classification = classify_risk(final_score)

    print("Message:", message)
    print("Text Risk Score:", text_score)
    print("URL Risk Score:", url_score)
    print("Final Risk Score:", final_score)
    print("Risk Level:", classification)

analyze_message("URGENT! Verify your bank account now http://fakebank-login.com/update")

def analyze_message(message):
    text_score = text_risk_score(message)
    url_score = url_risk_score(message)
    final_score = final_risk_score(message)
    classification = classify_risk(final_score)

    print("\n--- SCAM ANALYSIS REPORT ---")
    print("Message:", message)
    print("Text Risk Score:", text_score)
    print("URL Risk Score:", url_score)
    print("Final Risk Score:", final_score)
    print("Risk Level:", classification)

    if classification == "HIGH RISK 🔴":
        print("⚠️ This message shows strong scam indicators.")
    elif classification == "MEDIUM RISK 🟡":
        print("⚠️ This message contains suspicious patterns.")
    else:
        print("✅ This message appears safe.")

msg = "URGENT! Verify your bank account now http://fakebank-login.com/update"

print("Final Risk Score:", final_risk_score(msg))
print("Risk Level:", classify_risk(final_risk_score(msg)))

def final_risk_score(message):
    text_score = text_risk_score(message)
    url_score = url_risk_score(message)

    final_score = (0.5 * text_score) + (0.5 * url_score)

    # Security override rule
    if url_score >= 70:
        final_score = 85   # force high-risk scenario

    return round(final_score, 2)

msg = "URGENT! Verify your bank account now http://fakebank-login.com/update"

print("Text Risk:", text_risk_score(msg))
print("URL Risk:", url_risk_score(msg))
print("Final Risk Score:", final_risk_score(msg))
print("Risk Level:", classify_risk(final_risk_score(msg)))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predict directly using raw X_test
y_pred = model.predict(X_test)

print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

import pandas as pd

df = pd.read_csv("sms.tsv", sep="\t", header=None, names=["label", "message"])

df["label"] = df["label"].map({"ham": 0, "spam": 1})

X = df["message"]
y = df["label"]